// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBKuAsY0jlJVRCa2jw1EsqI5PHgaAk3Tmw',
//     appId: '1:335830297144:web:cee0e3e89c9b610508d4cd',
//     messagingSenderId: '335830297144',
//     projectId: 'nej-drivers',
//     authDomain: 'nej-drivers.firebaseapp.com',
//     storageBucket: 'nej-drivers.appspot.com',
//     measurementId: 'G-9CL17NY4M3',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBGgykLNuVK6tcFquJP3z-OgjX2Cp-eU2U',
//     appId: '1:335830297144:android:8f43750acdd27a0408d4cd',
//     messagingSenderId: '335830297144',
//     projectId: 'nej-drivers',
//     storageBucket: 'nej-drivers.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBXF3YIb-FGLHyVDsFxVxu7lq1XgVoeJsw',
//     appId: '1:335830297144:ios:155ad0ac62c6196b08d4cd',
//     messagingSenderId: '335830297144',
//     projectId: 'nej-drivers',
//     storageBucket: 'nej-drivers.appspot.com',
//     iosClientId: '335830297144-eussbth4dqocqk0j7bgjlvp2b8uftfsv.apps.googleusercontent.com',
//     iosBundleId: 'com.nej.drivers',
//   );
// }
