// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6trXRalfkWewhBzC6NjQ7pX3Dr_jXXv4',
    appId: '1:197977133555:web:2c55835293c239a20e8286',
    messagingSenderId: '197977133555',
    projectId: 'dulcetdash-drivers',
    authDomain: 'dulcetdash-drivers.firebaseapp.com',
    storageBucket: 'dulcetdash-drivers.appspot.com',
    measurementId: 'G-D34PQSEN7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCQ9RU8502n0YAgr6_z0AXocw32TZmeQ',
    appId: '1:197977133555:android:9c8544a4f72468940e8286',
    messagingSenderId: '197977133555',
    projectId: 'dulcetdash-drivers',
    storageBucket: 'dulcetdash-drivers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7rHEoop0JQ5RAudBZ67xQdZCX22AypAI',
    appId: '1:197977133555:ios:1e5e6953ceb7be720e8286',
    messagingSenderId: '197977133555',
    projectId: 'dulcetdash-drivers',
    storageBucket: 'dulcetdash-drivers.appspot.com',
    iosBundleId: 'com.drivers.dulcetdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7rHEoop0JQ5RAudBZ67xQdZCX22AypAI',
    appId: '1:197977133555:ios:da9a95f9c88e52aa0e8286',
    messagingSenderId: '197977133555',
    projectId: 'dulcetdash-drivers',
    storageBucket: 'dulcetdash-drivers.appspot.com',
    iosBundleId: 'com.example.shoppersApp.RunnerTests',
  );
}
